#!/bin/bash
cd src
headers=( *_module.h )
echo "// !!!WARNING!!! This file is auto generated by update_dispatcher.sh. Don't edit it manually." > dispatcher_module_init.cpp
for i in ${headers[@]}
do
    echo "#include \"$i\"" >> dispatcher_module_init.cpp
done

echo "

Dispatcher::Dispatcher() : CLI_Module(\"help\", 0)
{
    //Add all modules we know about to a vector for lookup
    _modules.push_back(this);
" >> dispatcher_module_init.cpp

for i in ${headers[@]}
do
    if [ $i != "dispatcher_module.h" ] && [ $i != "cli_module.h" ]
    then
        keyword=${i%%_module.h}
        echo "    _modules.push_back(new CLI_${keyword^}());" >> dispatcher_module_init.cpp
    fi
done  

echo "}" >> dispatcher_module_init.cpp
