// !!!WARNING!!! This file is auto generated by update_dispatcher.sh. Don't edit it manually.
#include "cli_module.h"
#include "color_module.h"
#include "dispatcher_module.h"
#include "draw_module.h"
#include "echo_module.h"
#include "lookat_module.h"
#include "move_module.h"
#include "ortho_module.h"
#include "perspective_module.h"
#include "pop_module.h"
#include "printcamera_module.h"
#include "printortho_module.h"
#include "printperspect_module.h"
#include "push_module.h"
#include "read_module.h"
#include "reset_module.h"
#include "resize_module.h"
#include "rotate_module.h"
#include "scale_module.h"
#include "select_module.h"
#include "stacktop_module.h"
#include "tiffread_module.h"
#include "tiffstat_module.h"
#include "tiffwrite_module.h"
#include "translate_module.h"
#include "vertex_module.h"
#include "zoom_module.h"


Dispatcher::Dispatcher() : CLI_Module("help", 0)
{
    //Add all modules we know about to a vector for lookup
    _modules.push_back(this);

    _modules.push_back(new CLI_Color());
    _modules.push_back(new CLI_Draw());
    _modules.push_back(new CLI_Echo());
    _modules.push_back(new CLI_Lookat());
    _modules.push_back(new CLI_Move());
    _modules.push_back(new CLI_Ortho());
    _modules.push_back(new CLI_Perspective());
    _modules.push_back(new CLI_Pop());
    _modules.push_back(new CLI_Printcamera());
    _modules.push_back(new CLI_Printortho());
    _modules.push_back(new CLI_Printperspect());
    _modules.push_back(new CLI_Push());
    _modules.push_back(new CLI_Read());
    _modules.push_back(new CLI_Reset());
    _modules.push_back(new CLI_Resize());
    _modules.push_back(new CLI_Rotate());
    _modules.push_back(new CLI_Scale());
    _modules.push_back(new CLI_Select());
    _modules.push_back(new CLI_Stacktop());
    _modules.push_back(new CLI_Tiffread());
    _modules.push_back(new CLI_Tiffstat());
    _modules.push_back(new CLI_Tiffwrite());
    _modules.push_back(new CLI_Translate());
    _modules.push_back(new CLI_Vertex());
    _modules.push_back(new CLI_Zoom());
}
